import { generatorHandler } from "@prisma/generator-helper";
import { writeFile } from "fs";
import { resolve } from "path";

const header = `/**
 * This file was generated by a custom prisma generator, do not edit it manually.
 * This allows usage of the generated Prisma Enums to be used on the client side.
 * We re-export this file from the \`@agreeto/api\` package, since it's more widely used.
 **/\n
`;

generatorHandler({
  onManifest() {
    return {
      defaultOutput: "../client-types.ts",
      prettyName: "Prisma Enum Generator",
    };
  },
  async onGenerate(options) {
    const enums = options.dmmf.datamodel.enums;

    const output = enums.map((e) => {
      let enumString = `export const ${e.name} = {\n`;
      e.values.forEach(({ name: value }) => {
        enumString += `  ${value}: "${value}",\n`;
      });
      enumString += `} as const;\n\n`;
      enumString += `export type ${e.name} = typeof ${e.name}[keyof typeof ${e.name}];\n`;

      return enumString;
    });

    const outputFile = options.generator.output;
    if (!outputFile) {
      throw new Error("No output file specified");
    }

    const outputPath = resolve(outputFile.value);
    writeFile(outputPath, header + output.join("\n"), "utf-8", (err) => {
      console.error("Error writing generated file", err);
    });
  },
});
