import type { NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  // FIXME: This isn't updated when I initiate the sign in from the extension?
  // Maybe because the component renders for session.data?.user and the user addition has been buggy
  const session = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container flex flex-col items-center justify-center min-h-screen p-4 mx-auto">
        {/* AUTHENTICATION STATUS */}
        {session.data?.user ? (
          <>
            <h4 className="text-xl">Signed in as {session.data.user.email}</h4>
            <p>You can log out via the extension</p>
          </>
        ) : (
          <h4>You&apos;re not signed in. Please use the extension to do so!</h4>
        )}
        {/* /AUTHENTICATION STATUS */}
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Create <span className="text-purple-300">T3</span> App
        </h1>
        <div className="flex items-center justify-center w-full pt-6 text-2xl text-blue-500"></div>
      </main>
    </>
  );
};

export default Home;
