import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { Button, Dialog } from "@agreeto/ui";

const startDate = new Date("2021-01-01T00:00:00.000Z");
const endDate = new Date("2022-12-31T23:59:59.999Z");

const Home: NextPage = () => {
  const currentUser = trpc.user.me.useQuery();
  const eventQuery = trpc.event.all.useQuery({ startDate, endDate });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center gap-2">
        {/* SOME UI */}
        <Dialog
          trigger={<Button>Delete account</Button>}
          variant="error"
          title="Delete Account"
          description="Are you sure you want to delete your account?"
          actionLabel="Yes, delete"
        />
        {/* AUTHENTICATION STATUS */}
        {currentUser.data ? (
          <>
            <h4 className="text-xl">Signed in as {currentUser.data.email}</h4>
            <p>You can log out via the extension</p>
          </>
        ) : (
          <h4>You&apos;re not signed in. Please use the extension to do so!</h4>
        )}
        {/* /AUTHENTICATION STATUS */}

        <pre className="w-4/5 overflow-scroll bg-gray-200">
          {JSON.stringify(eventQuery.data, null, 2)}
        </pre>
      </main>
    </>
  );
};

export default Home;
