export const azureScopes = [
  "user.read",
  "openid",
  "profile",
  "email",
  "offline_access",
  "Calendars.Read",
  "Calendars.ReadWrite",
  "Calendars.Read",
  "OnlineMeetings.Read",
  "OnlineMeetings.ReadWrite",
  "https://graph.microsoft.com/user.read",
  "https://graph.microsoft.com/openid",
  "https://graph.microsoft.com/profile",
  "https://graph.microsoft.com/email",
  "https://graph.microsoft.com/offline_access",
  "https://graph.microsoft.com/Calendars.Read",
  "https://graph.microsoft.com/Calendars.ReadWrite",
  "https://graph.microsoft.com/Calendars.Read",
  "https://graph.microsoft.com/OnlineMeetings.Read",
  "https://graph.microsoft.com/OnlineMeetings.ReadWrite",
];

export const googleScopes = [
  "openid",
  "https://www.googleapis.com/auth/calendar.readonly",
  "https://www.googleapis.com/auth/userinfo.email",
  "https://www.googleapis.com/auth/userinfo.profile",
  "https://www.googleapis.com/auth/calendar.events",
  "https://www.googleapis.com/auth/admin.directory.user.readonly",
];
