/**
 * This file was generated by a custom prisma generator, do not edit it manually.
 * This allows usage of the generated Prisma Enums to be used on the client side.
 * We re-export this file from the `@agreeto/api` package, since it's more widely used.
 **/

export const Language = {
  EN: "EN",
  DE: "DE",
  IT: "IT",
  FR: "FR",
  ES: "ES",
} as const;

export type Language = typeof Language[keyof typeof Language];

export const EventCalendarType = {
  BLOCKER: "BLOCKER",
} as const;

export type EventCalendarType =
  typeof EventCalendarType[keyof typeof EventCalendarType];

export const EventResponseStatus = {
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
  NEEDS_ACTION: "NEEDS_ACTION",
  TENTATIVE: "TENTATIVE",
} as const;

export type EventResponseStatus =
  typeof EventResponseStatus[keyof typeof EventResponseStatus];

export const Membership = {
  FREE: "FREE",
  TRIAL: "TRIAL",
  PRO: "PRO",
  PREMIUM: "PREMIUM",
} as const;

export type Membership = typeof Membership[keyof typeof Membership];
